### ISSUE TITLE
Sub-folder navigation

### ISSUE THREAD

**Issue by GingkathFox** [GingkathFox/WIP_Bot_Discord#5]
@theGordHoard this thing jittin. as you can see, i moved `randNick.js` to a seperate folder, but Node throws this error:
```C:\Users\GingkathFox\Downloads\WIP_Bot_Discord-master\WIP_Bot_Discord-master>node Test-Bot
module.js:549
    throw err;
    ^

Error: Cannot find module './commands/functions'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\GingkathFox\Downloads\WIP_Bot_Discord-master\WIP_Bot_Discord-master\Test-Bot.js:10:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)```
theres no `./commands/functions` as far as i can see, and it says its in the main bot file.

**Comment by GingkathFox** [comment]
looking back at this, i realize i was very stupid and this is so bad i dont ever want to see it again
